POST http://localhost:3333/anime
Content-Type: application/json

{
    "nome": "Bleach",
    "diretor": "Chihiro",
    "duracao": 24
}

###

GET http://localhost:3333/anime

###

GET http://localhost:3333/anime?search=Naruto

###

PUT http://localhost:3333/anime/09b18339-3b07-4d07-ab37-3c0e5ffe6ec1
Content-Type: application/json

{
    "nome": "Naruto",
    "diretor": "Sojo",
    "duracao": 24
}

###

DELETE http://localhost:3333/anime/09b18339-3b07-4d07-ab37-3c0e5ffe6ec1